/** Twenty seconds of dodging the witch's spells. One hit turns the player into a frog. */
class BossBattleController {
  constructor(){this.active=false;this.createDOM();}
  createDOM(){this.overlay=document.createElement('div');this.overlay.className='boss-overlay hidden';this.overlay.innerHTML=`<div class="boss-box"><div class="witch-big pixel-witch"><i></i><b></b></div><div class="boss-title">THE VERY NORMAL WITCH</div><div class="boss-rule">DODGE EVERY SPELL FOR 20 SECONDS — ONE HIT = FROG FOREVER</div><div id="bossTimer" class="boss-timer">20.0</div><canvas id="bossCanvas" width="560" height="400"></canvas></div>`;document.body.appendChild(this.overlay);this.canvas=this.overlay.querySelector('#bossCanvas');this.ctx=this.canvas.getContext('2d');this.winOverlay=document.createElement('div');this.winOverlay.className='disco-overlay hidden';this.winOverlay.innerHTML='<div class="disco-title">WITCH DEFEATED! DISCO TIME!!</div><div class="disco-dancers"><i></i><i></i><i></i><i></i><i></i></div>';document.body.appendChild(this.winOverlay);}
  start(){this.active=true;this.player={x:280,y:320,s:14};this.spells=[];this.last=performance.now();this.started=this.last;this.spawnClock=0;this.overlay.classList.remove('hidden');Sound.setBossMusic(true);requestAnimationFrame(t=>this.loop(t));}
  loop(now){if(!this.active)return;const dt=Math.min(60,now-this.last);this.last=now;const elapsed=(now-this.started)/1000,remaining=Math.max(0,20-elapsed);this.overlay.querySelector('#bossTimer').textContent=remaining.toFixed(1);this.move(dt);this.spawnClock+=dt;if(this.spawnClock>300){this.spawnClock=0;this.spawnSpell();}this.spells.forEach(s=>{s.x+=s.vx*dt/1000;s.y+=s.vy*dt/1000;});this.spells=this.spells.filter(s=>s.x>-30&&s.x<590&&s.y>-30&&s.y<430);if(this.spells.some(s=>Math.hypot(s.x-this.player.x,s.y-this.player.y)<s.r+this.player.s)){this.lose();return;}this.draw();if(remaining<=0){this.win();return;}requestAnimationFrame(t=>this.loop(t));}
  move(dt){let x=0,y=0;if(Input.keys.left)x--;if(Input.keys.right)x++;if(Input.keys.up)y--;if(Input.keys.down)y++;if(x&&y){x*=.707;y*=.707;}this.player.x=Math.max(12,Math.min(548,this.player.x+x*205*dt/1000));this.player.y=Math.max(12,Math.min(388,this.player.y+y*205*dt/1000));}
  spawnSpell(){const side=Math.floor(Math.random()*4),angle=Math.atan2(this.player.y-200,this.player.x-280)+(Math.random()-.5)*1.55;let x,y;if(side===0){x=Math.random()*560;y=-15;}else if(side===1){x=575;y=Math.random()*400;}else if(side===2){x=Math.random()*560;y=415;}else{x=-15;y=Math.random()*400;}const a=Math.atan2(this.player.y-y,this.player.x-x)+(Math.random()-.5)*.38,speed=110+Math.random()*70;this.spells.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:7+Math.random()*5,color:['#ff6caa','#b879ff','#66e7df','#ffe36f'][Math.floor(Math.random()*4)]});}
  draw(){const c=this.ctx;c.fillStyle='#0b0714';c.fillRect(0,0,560,400);c.strokeStyle='#2a1740';for(let i=0;i<560;i+=28){c.beginPath();c.moveTo(i,0);c.lineTo(i,400);c.stroke();}this.spells.forEach(s=>{c.fillStyle=s.color;c.beginPath();c.arc(s.x,s.y,s.r,0,Math.PI*2);c.fill();});c.fillStyle='#fff5d7';c.fillRect(this.player.x-this.player.s,this.player.y-this.player.s,this.player.s*2,this.player.s*2);c.fillStyle='#d9448d';c.fillRect(this.player.x-5,this.player.y-5,10,10);}
  lose(){this.active=false;this.overlay.classList.add('hidden');Sound.setBossMusic(false);window.gameInstance.turnIntoFrog();}
  win(){this.active=false;this.overlay.classList.add('hidden');Sound.setBossMusic(false);Sound.setDiscoMusic(true);this.winOverlay.classList.remove('hidden');Sound.playDisco();setTimeout(()=>{this.winOverlay.classList.add('hidden');Sound.setDiscoMusic(false);},4300);}
}
const BossBattle=new BossBattleController();
